In [1]:
import numpy as np
rng = np.random.default_rng(12345)
rints = rng.integers(low=0, high=10, size=3)
rints

array([6, 2, 7], dtype=int64)

In [2]:
rng = np.random.default_rng(12345)
#从一个均匀分布[low,high)中随机采样
rng.uniform(size=(5,2))

array([[0.22733602, 0.31675834],
       [0.79736546, 0.67625467],
       [0.39110955, 0.33281393],
       [0.59830875, 0.18673419],
       [0.67275604, 0.94180287]])

In [3]:
# 随机生成0-100之间的数字
np.random.randint(0,10,10)*10

array([30, 90, 10,  0, 70, 20, 50, 40, 20, 90])

In [15]:
# 随机生成0-100之间的4行3列的数组
np.random.randint(0,10,(4,3))*10

array([[ 0, 50, 60],
       [90, 70, 90],
       [50, 60, 10],
       [ 0, 70, 60]])

In [4]:
# 随机生成0-100之间的正太分布的数组(10,1)
np.random.normal(0,100,(10,1))

array([[-155.56457276],
       [   1.92185444],
       [ 138.62722478],
       [ -35.68680354],
       [  39.44130155],
       [ -78.09958262],
       [ -47.52493685],
       [ -49.72518396],
       [  47.84553698],
       [ -38.32108857]])

In [5]:
# 随机生成-1，1之间的二维数组(100,1)
np.random.choice(a=[-1,1],size=(10,1))

array([[ 1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [-1],
       [-1],
       [ 1],
       [-1],
       [-1]])

In [6]:
a = np.random.normal(0,100,(10,1))
print(a)
b = np.random.choice(a=[-1,1], size=(10,1))
print(b)

[[  32.99925616]
 [-159.38504108]
 [ 146.94159089]
 [  76.35753891]
 [-159.19247488]
 [-217.61194578]
 [  48.74923556]
 [  33.87137542]
 [  64.82042605]
 [  78.93642813]]
[[ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [-1]]


In [7]:
c = np.c_[a,b]
print(c)

[[  32.99925616    1.        ]
 [-159.38504108    1.        ]
 [ 146.94159089   -1.        ]
 [  76.35753891   -1.        ]
 [-159.19247488    1.        ]
 [-217.61194578    1.        ]
 [  48.74923556    1.        ]
 [  33.87137542   -1.        ]
 [  64.82042605   -1.        ]
 [  78.93642813   -1.        ]]


In [8]:
a1 = np.random.choice(a=[-10,10],size=(1000))
# print(a1)
print(np.sum(a1))

0


In [9]:
#生成0到10,间隔为10/5的数组
np.arange(0,10,10/5)

array([0., 2., 4., 6., 8.])

In [10]:
np.random.randint(-10, 10, size=(10,))

array([ 9,  3, -2,  8, -8,  5, -2, -8,  4,  6])

In [11]:
np.random.uniform(0, 5, size=10)

array([1.53523024, 1.35446028, 2.65157922, 3.8583671 , 3.86098785,
       0.76285724, 3.98388   , 2.57121123, 3.80204131, 4.63229349])