In [2]:
import numpy as np

1 np.arange(),类似于range，通过指定开始值，终值和步长来创建表示等差数列的一维数组，注意该函数和range一样结果不包含终值。

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

2 np.linspace()函数，与上面np.arange不同的是，该函数第三个参数指定的是元素个数，它表示给定起始值和终点值以及元素个数，生成一个一维的等差数列。含有参数endpoint布尔值，默认为True表示包含终值，设定为False表示不包含终值。


In [5]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.linspace(0, 1, 10, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

3 np.logspace,该函数与np.linspace类似，不过它生成的数组是等比数列，基数默认为10

其中a、b、n分别表示开始值（2^a）、结束值(2^b)、元素个数(n)。

In [7]:
# 用法：logspace(a,b,n,base=2)，
# 其中a、b、n分别表示开始值（2^a）、结束值(2^b)、元素个数(n)。
np.logspace(0, 3, 4, base=2)

array([1., 2., 4., 8.])

In [8]:
np.logspace(1, 3, 3, base=10)

array([  10.,  100., 1000.])

In [9]:
np.logspace(0, 3, 4, base=2)

array([1., 2., 4., 8.])

In [10]:
np.logspace(-1, 3, 5, base=2)

array([0.5, 1. , 2. , 4. , 8. ])

In [11]:
np.logspace(-2, 3, 6, base=2)

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

4. np.zeros(),np.ones(),np.empty()可以创建指定的形状和类型数组，其中np.enpty()只分配数组所使用的内存，不对数据初始化起作用。

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((2,3), np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [15]:
# np.enpty()只分配数组所使用的内存，不对数据初始化起作用。
np.empty((2,3), np.int32)

array([[         0, 1076101120,          0],
       [1079574528,          0, 1083129856]])

In [16]:
np.ones(4,dtype = np.bool)

C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([ True,  True,  True,  True])

In [17]:
# 函数可以生成初始化为指定值的数组
np.full(4, np.pi)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265])

此外np.zeros_like()，np.ones_like()等函数创建于参数形状相同的数组即np.zeros_like(a)与np.zeros(a.shape,dtype = a.type)相同

In [18]:
a = np.arange(10).reshape(2,5)
print(a)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
#创建形状2行5列 相同的全0 数组
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

5 np.fromfunction()，它可以从指定的函数中生成数组，第一个参数是函数名称，第二个参数是数组形状。

In [32]:
np.fromfunction(lambda i :i ,(4,))

array([0., 1., 2., 3.])

In [33]:
np.fromfunction(lambda  i,j: i+j, (3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [22]:
print(a)
np.fromfunction(lambda a,b: a == b,(3,3))

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
np.fromfunction(lambda i:i%7 +1,(10,))

array([1., 2., 3., 4., 5., 6., 7., 1., 2., 3.])

看到上述结果是不是觉得有点奇怪，也不清楚怎么来的。那下面我们来看看传给回调函数的i,j的值到底是啥？给函数多传个参数行不行呢？

In [24]:
def f(*args):
    print(args)
np.fromfunction(f,(2,3))

(array([[0., 0., 0.],
       [1., 1., 1.]]), array([[0., 1., 2.],
       [0., 1., 2.]]))


```python

#fromfunction源码
def fromfunction(function, shape, **kwargs):
    dtype = kwargs.pop('dtype', float)
    args = indices(shape, dtype=dtype)
    return function(*args,**kwargs)
#从源代码看,indices如何把shape参数转为对应的i,j参数，下面看看indices用法
#numpy.indices(dimensions, dtype=<type 'int'>)：子数组包含仅沿对应轴变化的索引值
args = np.indices((2,3))#等同np.mgrid[0:2,0:3]
#args#array([[[0, 0, 0],[1, 1, 1]],[[0, 1, 2],[0, 1, 2]]])
i,j=args
i #array([[0, 0, 0],[1, 1, 1]])
j #array([[0, 1, 2],[0, 1, 2]])
i+j#array([[0, 1, 2],[1, 2, 3]])两数组对应元素级相加
#结论：shape参数决定了输出数组的形状

```

In [25]:
def  f(x,y):
    print('x=\n',x,'\ny=\n', y)
    return x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

x=
 [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]] 
y=
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [26]:
# 随机生成一个2行4列,正态分布数组
a = np.random.randn(2,4)
print(a)
b = a[a<0]
print(b)

[[ 0.96237082 -0.21151456 -1.0558086  -1.037503  ]
 [-0.47999912  0.81680126  1.28031071  0.11216165]]
[-0.21151456 -1.0558086  -1.037503   -0.47999912]


In [27]:
#创建一个数据的二维数组
a = np.array([[0.15],])
print(a.shape, a.ndim)

(1, 1) 2


In [34]:
# 随机生成0-100之间的4行3列的数组
d1 = np.random.randint(0,10,(4,3))*10
d1

array([[10,  0, 30],
       [50, 80, 60],
       [40, 40, 70],
       [50, 80,  0]])

In [43]:
# 找出数据中最大和最小的值组成新的数组
np.hstack((np.amax(d1,axis=1).reshape(-1,1),np.amin(d1,axis=1).reshape(-1,1)))

array([[30,  0],
       [80, 50],
       [70, 40],
       [80,  0]])

In [48]:
d2 = np.random.randint(0,10,(4,2))*10
d2

array([[30, 20],
       [60, 60],
       [80, 50],
       [30, 20]])