In [3]:
import numpy as np
rng = np.random.default_rng(12345)
rints = rng.integers(low=0, high=10, size=3)
rints

array([6, 2, 7], dtype=int64)

In [4]:
rng = np.random.default_rng(12345)
#从一个均匀分布[low,high)中随机采样
rng.uniform(size=(5,2))

array([[0.22733602, 0.31675834],
       [0.79736546, 0.67625467],
       [0.39110955, 0.33281393],
       [0.59830875, 0.18673419],
       [0.67275604, 0.94180287]])

In [50]:
# 随机生成0-100之间的数字
np.random.randint(0,10,10)*10

array([90, 90, 20, 30, 20, 10,  0, 70, 50, 40])

In [48]:
# 随机生成0-100之间的正太分布的数组(10,1)
np.random.normal(0,100,(10,1))

array([[  63.65926636],
       [  58.06301854],
       [ -24.44102202],
       [  53.50430304],
       [   7.43411462],
       [ -89.16508034],
       [ -63.91936744],
       [ 177.5832377 ],
       [-245.15680971],
       [  -2.48158554]])

In [7]:
# 随机生成-1，1之间的二维数组(100,1)
np.random.choice(a=[-1,1],size=(10,1))

array([[ 1],
       [ 1],
       [ 1],
       [-1],
       [-1],
       [-1],
       [ 1],
       [ 1],
       [-1],
       [ 1]])

In [8]:
a = np.random.normal(0,100,(10,1))
print(a)
b = np.random.choice(a=[-1,1], size=(10,1))
print(b)

[[ -34.93571556]
 [ 195.74155622]
 [ 198.68687871]
 [-295.31955185]
 [ -13.51659068]
 [-122.99252588]
 [   7.2972833 ]
 [  36.23226633]
 [ -91.97906669]
 [  39.95524425]]
[[-1]
 [ 1]
 [ 1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [ 1]
 [ 1]
 [ 1]]


In [9]:
c = np.c_[a,b]
print(c)

[[ -34.93571556   -1.        ]
 [ 195.74155622    1.        ]
 [ 198.68687871    1.        ]
 [-295.31955185   -1.        ]
 [ -13.51659068    1.        ]
 [-122.99252588    1.        ]
 [   7.2972833    -1.        ]
 [  36.23226633    1.        ]
 [ -91.97906669    1.        ]
 [  39.95524425    1.        ]]


In [47]:
a1 = np.random.choice(a=[-10,10],size=(1000))
# print(a1)
print(np.sum(a1))

380


In [53]:
#生成0到10,间隔为10/5的数组
np.arange(0,10,10/5)

array([0., 2., 4., 6., 8.])

In [56]:
np.random.randint(-10, 10, size=(10,))

array([ -4,  -2,  -5, -10,  -3,  -4,   2,  -6,   8,  -3])

In [58]:
np.random.uniform(0, 5, size=10)

array([4.0842732 , 2.469922  , 3.0053854 , 4.75550396, 0.64166566,
       2.91651249, 3.08296726, 1.80096942, 3.17003352, 1.91150848])