### 导入包

In [123]:
# -*- conding: utf-8 -*-
import numpy as np

In [124]:
# reshape 改变数组的维度
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [125]:
# 数组的维度
a.shape

(3, 5)

In [126]:
# 数组的轴（维度）
a.ndim

2

In [127]:
# 数组中元素的类型
a.dtype.name

'int32'

In [128]:
# 数组中每个元素的大小
a.itemsize

4

In [129]:
# 数组中元素的个数
a.size

15

In [130]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [131]:
type(b)

numpy.ndarray

In [132]:
# 数组创建
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [133]:
a.dtype

dtype('int32')

In [134]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [135]:
# 一个常见的错误，就是调用array的时候传入多个数字参数，而不是提供单个数字的列表类型作为参数

In [136]:
a = np.array(1, 2, 3, 4)  # 错误的

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [ ]:
a = np.array([1, 2, 3, 4])  # 正确的
a

In [ ]:
# shape 数组的维度 这是一个整数的元组表示每个维度中数组的大小。对于有 n 行和 m 列的矩阵，shape 将是 (n,m)。

In [ ]:
a.shape

In [ ]:
a.ndim  # 数组的轴（维度）

In [ ]:
a.dtype

In [ ]:
# array 还可以将序列的序列转换成二维数组，将序列的序列的序列转换成三维数组，等等。

In [ ]:
b = np.array([(1.5, 2.3), (4, 5, 6)], dtype=object)
b

In [ ]:
# 也可以在创建时显式指定数组的类型

In [ ]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

In [ ]:
# 函数zeros创建一个由0组成的数组，函数 ones创建一个完整的数组，函数empty 创建一个数组，
# 其初始内容是随机的，取决于内存的状态。默认情况下，创建的数组的dtype是 float64 类型的

In [ ]:
a = np.zeros((3, 4))
a

In [ ]:
a.dtype

In [ ]:
np.ones((2, 3, 4), dtype=np.int16)

### 基础操作

In [ ]:
a = np.array([20, 30, 40, 50])
print(a)
b = np.arange(4)
print(b)

In [ ]:
c = a - b
print(c)

In [ ]:
b ** 2

In [ ]:
import numpy as np

# 二行1列二维数组，按位操作
a = np.array([[1, 1],])
b = np.array(([[0, 1],]))
a | b

In [ ]:
a = np.array([[1, 1], [0, 1]])
b = np.array([[2, 0], [3, 4]])
a * b

In [ ]:
a @ b

In [ ]:
a.dot(b)

In [ ]:
# 生成一个二行三列的全为1的数组
a = np.ones((2, 3), dtype=int)
a

In [ ]:
a *= 3
print(a)

In [ ]:
# 生成一个二行三列的随机数# 生成一个二行三列的随机数组
b = np.random.random((2, 3))
b

In [ ]:
b += a
b

In [ ]:
# b不会自动转换为整数类型
a += b

### 索引、切片和迭代

In [ ]:
# 一维的数组可以进行索引、切片和迭代操作的就像列表一样
a = np.arange(10) ** 1
a

In [ ]:
a[2:5]

In [ ]:
# 取0>=下标>6, 间隔为2的数据
a[:6:2]

In [ ]:
a[:6:2] = 100
a

In [ ]:
# 多维的数组每个轴可以有一个索引。这些索引以逗号隔的元组给出

In [ ]:
def f(x, y):
    return 10 * x + y

In [ ]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

In [ ]:
b[2, 3]

In [ ]:
# 取行下标0到5-1行，列下标1列的数据
b[0:5, 1]

In [ ]:
b[:, 1]

In [ ]:
# 取行下标1到3-1行，所有列的数据
b[1:3, :]

In [ ]:
# 取最后第一行数据
b[-1, :]

In [ ]:
b[-1, ...]

In [ ]:
# 当提供的索引少于轴的数量时，缺失的索引被认为是完整的切片
# 取最后一行数据,等价于 b[-1, :]和b[-1, ...]
# 三个点（ ... ）表示产生完整索引元组所需的冒号
b[-1]

In [ ]:
b[..., 3]

In [ ]:
b[..., -1]

In [ ]:
# 取最后一列数据 等价于 b[..., 3]和b[..., -1]
b[:, -1]

In [ ]:
# 三个点（ ... ）表示产生完整索引元组所需的冒号
for row in b:
    print(row)

In [ ]:
# 但是，如果想要对数组中的每个元素执行操作，可以使用flat属性，该属性是数组的所有元素的迭代器
for element in b.flat:
    print(element)

### 形状操作

In [ ]:
# 改变数据的形状
a = np.floor(10 * np.random.random((3, 4)))
a

In [ ]:
a.shape

In [ ]:
# 可以使用各种命令更改数组的形状。请注意，以下三个命令都返回一个修改后的数组，但不会更改原始数组
a.ravel()

In [ ]:
a.reshape(6, 2)  # 6行2列
# a.reshape(1, -1)  # 1行n列

In [ ]:
# 字体标题
np.dtype([(("字段标题", "字段名称"), "f4")])

### 数组运算

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array(
    [[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]]
)

In [ ]:
arr1.shape

In [ ]:
arr2 = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])

In [ ]:
arr2.shape

In [ ]:
arr1 + arr2

In [ ]:
# 用法：logspace(a,b,n,base=2)，
# 其中a、b、n分别表示开始值（2^a）、结束值(2^b)、元素个数(n)。
np.logspace(1, 4, 4, base=2)

In [ ]:
np.logspace(1,3,3,base=10)

In [ ]:
np.logspace(0,3,4,base=2)

In [ ]:
np.logspace(-1,3,5,base=2)

In [ ]:
np.logspace(-2,3,6,base=2)

 ravel()函数说明
 https://blog.csdn.net/liuweiyuxiang/article/details/78220080

In [ ]:
# import numpy as np
rng = np.random.RandomState(0)

X = 5 * rng.rand(10, 1)

y = np.sin(X).ravel() # 将多维数组降位一维
np.sin(X).ravel()


In [ ]:
# linspace 生成区间范围的一维数组
# -1到1区间，5个点，4个区间，平均分：[-1.,-0.25,0.5,1.25,2.]
new_ticks=np.linspace(-1,1,5)
new_ticks

In [ ]:
# 生成从0开始的3个数
np.arange(3)

In [212]:
#指定随机数每次运行都不一样
np.random.seed(0)
#指定概率，累加为1
p = ([0.3, 0.7])

In [213]:

#指定10%的概率取值为0，90%的概率取值为1

p1,p2 = 0, 0
for i in range(10000):
    value = np.random.choice([0,1], p = p)
    if value == 0:
        p1+=1
    else:
        p2+=1
print('p1=',p1)
print('p2=',p2)

p1= 1021
p2= 8979


第二种循环
count: 0
count: 1
count: 2
count: 3
count: 4
