### 导入包

In [83]:
# -*- conding: utf-8 -*-
import numpy as np

In [84]:
# reshape 改变数组的维度
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
# 数组的维度
a.shape

(3, 5)

In [86]:
# 数组的轴（维度）
a.ndim

2

In [123]:
# 数组中元素的类型
a.dtype.name

'int32'

In [88]:
# 数组中每个元素的大小
a.itemsize

4

In [89]:
# 数组中元素的个数
a.size

15

In [90]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [91]:
type(b)

numpy.ndarray

In [92]:
# 数组创建
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [93]:
a.dtype

dtype('int32')

In [94]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [95]:
# 一个常见的错误，就是调用array的时候传入多个数字参数，而不是提供单个数字的列表类型作为参数

In [96]:
# a = np.array(1, 2, 3, 4)  # 错误的

In [97]:
a = np.array([1, 2, 3, 4])  # 正确的
a

array([1, 2, 3, 4])

In [98]:
# shape 数组的维度 这是一个整数的元组表示每个维度中数组的大小。对于有 n 行和 m 列的矩阵，shape 将是 (n,m)。

In [99]:
a.shape

(4,)

In [100]:
a.ndim  # 数组的轴（维度）

1

In [101]:
a.dtype

dtype('int32')

In [102]:
# array 还可以将序列的序列转换成二维数组，将序列的序列的序列转换成三维数组，等等。

In [103]:
b = np.array([(1.5, 2.3), (4, 5, 6)], dtype=object)
b

array([(1.5, 2.3), (4, 5, 6)], dtype=object)

In [104]:
# 也可以在创建时显式指定数组的类型

In [105]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [106]:
# 函数zeros创建一个由0组成的数组，函数 ones创建一个完整的数组，函数empty 创建一个数组，
# 其初始内容是随机的，取决于内存的状态。默认情况下，创建的数组的dtype是 float64 类型的

In [107]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
a.dtype

dtype('float64')

In [109]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

### 基础操作

In [110]:
a = np.array([20, 30, 40, 50])
print(a)
b = np.arange(4)
print(b)

[20 30 40 50]
[0 1 2 3]


In [111]:
c = a - b
print(c)

[20 29 38 47]


In [112]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

In [3]:
import numpy as np

# 二行1列二维数组，按位操作
a = np.array([[1, 1], ])
b = np.array(([[0, 1], ]))
a | b

array([[1, 1]], dtype=int32)

In [114]:
a = np.array([[1, 1], [0, 1]])
b = np.array([[2, 0], [3, 4]])
a * b

array([[2, 0],
       [0, 4]])

In [115]:
a @ b

array([[5, 4],
       [3, 4]])

In [116]:
a.dot(b)

array([[5, 4],
       [3, 4]])

In [5]:
# 生成一个二行三列的全为1的数组
a = np.ones((2, 3), dtype=int)
a.shape

(2, 3)

In [20]:
rng = np.random.RandomState(2)
print(rng)
#从一个均匀分布[low,high)中随机采样
rng.uniform(size=(5,2))

RandomState(MT19937)


array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [118]:
a *= 3
print(a)

[[3 3 3]
 [3 3 3]]


In [1]:
# 生成一个二行三列的随机数# 生成一个二行三列的随机数组
b = np.random.random((2, 3))
b

NameError: name 'np' is not defined

In [120]:
b += a
b

array([[3.44501216, 3.78664532, 3.02808781],
       [3.19745157, 3.39540614, 3.15449298]])

In [121]:
# b不会自动转换为整数类型
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

### 索引、切片和迭代

In [ ]:
# 一维的数组可以进行索引、切片和迭代操作的就像列表一样
a = np.arange(10) ** 1
a

In [ ]:
a[2:5]

In [ ]:
# 取0>=下标>6, 间隔为2的数据
a[:6:2]

In [ ]:
a[:6:2] = 100
a

In [ ]:
# 多维的数组每个轴可以有一个索引。这些索引以逗号隔的元组给出

In [ ]:
def f(x, y):
    return 10 * x + y

In [ ]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

In [ ]:
b[2, 3]

In [ ]:
# 取行下标0到5-1行，列下标1列的数据
b[0:5, 1]

In [ ]:
b[:, 1]

In [ ]:
# 取行下标1到3-1行，所有列的数据
b[1:3, :]

In [ ]:
# 取最后第一行数据
b[-1, :]

In [ ]:
b[-1, ...]

In [ ]:
# 当提供的索引少于轴的数量时，缺失的索引被认为是完整的切片
# 取最后一行数据,等价于 b[-1, :]和b[-1, ...]
# 三个点（ ... ）表示产生完整索引元组所需的冒号
b[-1]

In [ ]:
b[..., 3]

In [ ]:
b[..., -1]

In [ ]:
# 取最后一列数据 等价于 b[..., 3]和b[..., -1]
b[:, -1]

In [ ]:
# 三个点（ ... ）表示产生完整索引元组所需的冒号
for row in b:
    print(row)

In [ ]:
# 但是，如果想要对数组中的每个元素执行操作，可以使用flat属性，该属性是数组的所有元素的迭代器
for element in b.flat:
    print(element)

### 形状操作

In [ ]:
# 改变数据的形状
a = np.floor(10 * np.random.random((3, 4)))
a

In [ ]:
a.shape

In [ ]:
# 可以使用各种命令更改数组的形状。请注意，以下三个命令都返回一个修改后的数组，但不会更改原始数组
a.ravel()

In [ ]:
a.reshape(6, 2)  # 6行2列
# a.reshape(1, -1)  # 1行n列

In [ ]:
# 字体标题
np.dtype([(("字段标题", "字段名称"), "f4")])

### 数组运算

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array(
    [[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]]
)

In [ ]:
arr1.shape

In [ ]:
arr2 = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])

In [ ]:
arr2.shape

In [ ]:
arr1 + arr2

In [ ]:
# 用法：logspace(a,b,n,base=2)，
# 其中a、b、n分别表示开始值（2^a）、结束值(2^b)、元素个数(n)。
np.logspace(1, 4, 4, base=2)

In [1]:
np.logspace(1, 3, 3, base=10)

NameError: name 'np' is not defined

In [ ]:
np.logspace(0, 3, 4, base=2)

In [ ]:
np.logspace(-1, 3, 5, base=2)

In [ ]:
np.logspace(-2, 3, 6, base=2)

 ravel()函数说明
 https://blog.csdn.net/liuweiyuxiang/article/details/78220080

In [ ]:
# import numpy as np
rng = np.random.RandomState(0)

X = 5 * rng.rand(10, 1)

y = np.sin(X).ravel()  # 将多维数组降位一维
np.sin(X).ravel()


In [ ]:
# linspace 生成区间范围的一维数组
# -1到1区间，5个点，4个区间，平均分：[-1.,-0.25,0.5,1.25,2.]
new_ticks = np.linspace(-1, 1, 5)
new_ticks

In [ ]:
# 生成从0开始的3个数
np.arange(3)

In [ ]:
# 生成从1开始,10以内,步长为2的数组
np.arange(1,10,2)

In [124]:
#指定随机数每次运行都不一样
np.random.seed(0)
#指定概率，累加为1
p = ([0.3, 0.7])

#指定10%的概率取值为0，90%的概率取值为1
p1, p2 = 0, 0
for i in range(10000):
    value = np.random.choice([0, 1], p=p)
    if value == 0:
        p1 += 1
    else:
        p2 += 1
print('p1=', p1)
print('p2=', p2)

p1= 3055
p2= 6945


In [189]:
# 生成size 个由 a 构成，且指定a数组中每个元素发生的概率为p 组成的数组
a = [-1, 1]  #随机数的构成元素
size = 100  #随机数组的大小
p=[0.5, 0.5]  #a中各元素的发生概率，合计为1， 且元素个数与a中的元素个数相等
arr = np.random.choice([-1, 1], 100, p=[0.5, 0.5])
arr

array([ 1,  1, -1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1, -1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1,  1,  1,  1,
        1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [131]:
# 指定30%的概率生成-1，70%的概率生成1的随机数生成器
p1, p2 = 0, 0
for i in range(1000):
    value = np.random.choice([-1, 1], p=[0.3, 0.7])
    if value == -1:
        p1 += 1
    elif value == 1:
        p2 += 1
print('p1=',p1)
print('p2=',p2)

p1= 319
p2= 681


In [175]:
# 生成指定概率各50%的由-1和1组成的数组
a1 = np.zeros(100)
for i in range(len(a1)):
    a1[int(i)] = np.random.choice([-1, 1], p=[0.5,0.5])
a1

array([ 1.,  1.,  1., -1.,  1., -1.,  1., -1., -1.,  1., -1.,  1., -1.,
       -1., -1., -1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1.,
        1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1.,  1., -1., -1., -1.,
       -1.,  1., -1.,  1., -1., -1.,  1., -1., -1.,  1., -1.,  1.,  1.,
       -1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,
       -1.,  1., -1.,  1., -1., -1.,  1., -1.,  1., -1., -1., -1.,  1.,
       -1., -1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
       -1.,  1., -1.,  1.,  1., -1.,  1., -1., -1.])

In [ ]:
np.random.choice()

In [149]:
# https://blog.csdn.net/robert_chen1988/article/details/102712946#:~:text=%E8%AE%A1%E7%AE%97%E6%96%B9%E5%B7%AE%E6%97%B6%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%88%A9%E7%94%A8%20numpy%20%E4%B8%AD%E7%9A%84%20var%20%E5%87%BD%E6%95%B0%EF%BC%8C%E9%BB%98%E8%AE%A4%E6%98%AF%E6%80%BB%E4%BD%93%E6%96%B9%E5%B7%AE%EF%BC%88%E8%AE%A1%E7%AE%97%E6%97%B6%E9%99%A4%E4%BB%A5%E6%A0%B7%E6%9C%AC%E6%95%B0%20N%EF%BC%89%EF%BC%8C%E8%8B%A5%E9%9C%80%E8%A6%81%E5%BE%97%E5%88%B0%E6%A0%B7%E6%9C%AC%E6%96%B9%E5%B7%AE%EF%BC%88%E8%AE%A1%E7%AE%97%E6%97%B6%E9%99%A4%E4%BB%A5%20N%20-,%E5%87%BD%E6%95%B0%E5%8F%AF%E4%BB%A5%E5%BE%97%E5%88%B0%E6%A0%B7%E6%9C%AC%E6%96%B9%E5%B7%AE%EF%BC%88%E6%B3%A8%E6%84%8F%E4%B8%8D%E6%98%AF%E6%80%BB%E4%BD%93%E6%96%B9%E5%B7%AE%EF%BC%89%EF%BC%8Cstd%20%E5%87%BD%E6%95%B0%E5%8F%AF%E4%BB%A5%E5%BE%97%E5%88%B0%E6%A0%B7%E6%9C%AC%E6%A0%87%E5%87%86%E5%B7%AE%EF%BC%8C%E8%8B%A5%E8%A6%81%E5%BE%97%E5%88%B0%E6%9F%90%E4%B8%80%E8%A1%8C%E6%88%96%E6%9F%90%E4%B8%80%E5%88%97%E7%9A%84%E6%96%B9%E5%B7%AE%EF%BC%8C%E5%88%99%E4%B9%9F%E5%8F%AF%E7%94%A8%20iloc%20%E9%80%89%E5%8F%96%E6%9F%90%E8%A1%8C%E6%88%96%E6%9F%90%E5%88%97%EF%BC%8C%E5%90%8E%E9%9D%A2%E5%86%8D%E8%B7%9F%20var%20%E5%87%BD%E6%95%B0%E6%88%96%20std%20%E5%87%BD%E6%95%B0%E5%8D%B3%E5%8F%AF%EF%BC%8C%E4%BE%8B%E5%A6%82%EF%BC%9A

# import numpy as np

# 生成2行4列，均值为0，方差为1的数组
a = np.random.randn(2, 4)
print(a)
# 指定数学期望和方差的正态分布 N(μ, σ2)
# σ2：分布的标准偏差（展开或"宽度"）数据的分散程度 μ：数学期望或均值
# 生成均值为5，标准差为 2.5 的正态分布的数组
# sigma * np.random.randn(...) + mu
a = 2.5 * np.random.randn(2, 4) + 5
np.random.randn()
# 生成均值为5，标准差为 2.5 正态分布的一维数组
b = np.random.normal(2.5, 5.0, 10)
print('b=', b)

print(a.shape)
print(a)
print('总体均值', np.mean(a))
print('每一行均值', np.average(a, axis=1))
print('加权平均', np.average(a, weights=a))
print('总体方差', np.var(a))
print('样本方差', np.var(a, ddof=1))
print('总体标准差', np.std(a))
print('每一列总体标准差', np.std(a, axis=0))
print('样本标准差', np.std(a, ddof=1))

[[-0.75870474  0.15113869  0.806744    0.33086943]
 [ 0.81301513 -0.43252299 -0.39968134  0.71243103]]
b= [ 5.6464141  -1.816038    3.74343368  0.20478425 -2.43383866  4.31348893
 -2.86504055 -5.67258766  3.97681152  3.58137291]
(2, 4)
[[6.39900697 8.10191554 1.22409665 3.08652118]
 [6.1024902  1.52673731 5.63160288 1.146503  ]]
总体均值 4.152359216575258
每一行均值 [4.70288509 3.60183335]
加权平均 5.726084709203325
总体方差 6.534673553673592
样本方差 7.468198347055534
总体标准差 2.5563007557158826
每一列总体标准差 [0.14825838 3.28758912 2.20375312 0.97000909]
样本标准差 2.732800458697183


In [34]:
# 生成均值为0，标准偏差为 10 正态分布的一维数组
mu, sigma = -10, 100 # mean and standard deviation
a = np.random.normal(mu, sigma, 100)

print(a[:10])
print(a.shape)
print('正数个数sum', np.sum(a>0))
print('总体均值mean', np.mean(a))
print('中位数med', np.median(a))
# print('每一行均值', np.average(a, axis=1))  #二维数组可用
print('加权平均avg', np.average(a, weights=a))
print('总体方差avr', np.var(a))
print('样本方差avr', np.var(a, ddof=1))
print('总体标准差std', np.std(a))
print('每一列总体标准差std', np.std(a, axis=0))
print('样本标准差std', np.std(a, ddof=1))

[ -75.51358214  -39.97481199  -58.28699735    3.40332218  241.89530812
 -189.80694952 -117.33094228  -12.62103694  -60.44165515 -185.32225443]
(100,)
正数个数sum 32
总体均值mean -39.27307962382786
中位数med -39.48092305034394
加权平均avg -246.4045822037411
总体方差avr 8134.691993424038
样本方差avr 8216.86059941822
总体标准差std 90.19252737019868
每一列总体标准差std 90.19252737019868
样本标准差std 90.64690066085117


np.random.normal 生成二维随机正态分布数组

In [35]:
# 生成均值为0，标准偏差为 10 正态分布的二维数组
mu, sigma, size = -10, 100, (100, 2) # mean and standard deviation
a = np.random.normal(mu, sigma, size)

print(a[:10])
print(a.shape)
print('正数个数sum', np.sum(a>0))
print('总体均值mean', np.mean(a))
print('中位数med', np.median(a))
# print('每一行均值', np.average(a, axis=1))
print('加权平均avg', np.average(a, weights=a))
print('总体方差avr', np.var(a))
print('样本方差avr', np.var(a, ddof=1))
print('总体标准差std', np.std(a))
print('每一列总体标准差std', np.std(a, axis=0))
print('样本标准差std', np.std(a, ddof=1))

[[ -47.40632252  122.77247818]
 [ -13.49915301 -145.05839099]
 [  48.78131068  -31.10848474]
 [-145.49367799  124.39011742]
 [  65.42121137   64.42929139]
 [ -36.60185361 -230.15467749]
 [  27.87133294   91.1265764 ]
 [  92.9745269  -101.67088685]
 [   4.21200266  -75.45449975]
 [  95.69485099   78.37206862]]
(100, 2)
正数个数sum 101
总体均值mean -4.597211060450194
中位数med 1.4148829343759468
加权平均avg -2041.0869882298564
总体方差avr 9362.173328096944
样本方差avr 9409.219425223058
总体标准差std 96.75832433489609
每一列总体标准差std [97.08371992 94.89505745]
样本标准差std 97.0011310512566


## 数组合并，拼接

numpy数组的合并有很多方法，如

np.append()
np.concatenate()
np.stack()
np.hstack()
np.vstack()
np.dstack()
其中最泛用的是第一个和第二个。第一个可读性好，比较灵活，但是占内存大。第二个则没有内存占用大的问题
————————————————
版权声明：本文为CSDN博主「赵至柔」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/qq_39516859/article/details/80666070

In [274]:
a1 = np.array([1,1,1])
b1 = np.array([2,2,2])

a2 = np.array([[1,1,1],
               [2,2,2],
               [3,3,3]])
b2 = np.array([[11,11,11],
               [22,22,22],
               [33,33,33]])

print(a1.shape)
print(a1.ndim)

(3,)
1


1、水平组合

In [295]:
print("--------------------")
print('a1=\n',a1)
print('b1=\n',b1)
print("--------------------")
ch1 = np.hstack((a1, b1))
print(ch1)
print(ch1.shape,ch1.ndim,'hstack一维数组水平组合,维度不变，个数增加')
cc1 = np.concatenate((a1, b1))
print(cc1)
print(cc1.shape,cc1.ndim,'concatenate与hstack一维数组水平组合一样')
print("--------------------")
print('a2=\n',a2)
print('b2=\n',b2)
print("--------------------")
ch2 = np.hstack((a2, b2))
print(ch2)
print(a2.shape,a2.ndim,ch2.shape,ch2.ndim,'hstack二维数组水平组合,维度不变,行数不变，列数改变')
# print(np.concatenate((a1, b1), axis=1))  #错误代码，一维数据
cc2 = np.concatenate((a2, b2), axis=1)
print(cc2.shape,cc2.ndim)

--------------------
a1=
 [1 1 1]
b1=
 [2 2 2]
--------------------
[1 1 1 2 2 2]
(6,) 1 hstack一维数组水平组合,维度不变，个数增加
[1 1 1 2 2 2]
(6,) 1 concatenate与hstack一维数组水平组合一样
--------------------
a2=
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
b2=
 [[11 11 11]
 [22 22 22]
 [33 33 33]]
--------------------
[[ 1  1  1 11 11 11]
 [ 2  2  2 22 22 22]
 [ 3  3  3 33 33 33]]
(3, 3) 2 (3, 6) 2 hstack一维数组水平组合,维度不变,行数不变，列数改变
(3, 6) 2


2、垂直组合

In [290]:
print("--------------------")
print('a1=\n',a1)
print('b1=\n',b1)
print("--------------------")
cv1 = np.vstack((a1, b1))
print(cv1)
print(cv1.shape,cv1.ndim,'vstack一维数组垂直组合，数组变成二维')
cc2 = np.concatenate((a1, b1), axis=0)
print(cc2)
print(cc2.shape,cc2.ndim,'concatenate一维数组垂直组合，数组还是一维')
print("--------------------")
print('a2=\n',a2)
print('b2=\n',b2)
print("--------------------")
cv2 = np.vstack((a2, b2))
print(cv2)
print(cv2.shape,cv2.ndim,'vstack二维数组垂直组合，维度不变，列数不变，行数增加')
cc2 = np.concatenate((a2, b2), axis=0)
print(cc2)
print(cc2.shape,cc2.ndim,'concatenate与vstack二维数组垂直组合一样')

--------------------
a1=
 [1 1 1]
b1=
 [2 2 2]
--------------------
[[1 1 1]
 [2 2 2]]
(2, 3) 2 vstack一维数组垂直组合，数组变成二维
[1 1 1 2 2 2]
(6,) 1 concatenate一维数组垂直组合，数组还是一维
--------------------
a2=
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
b2=
 [[11 11 11]
 [22 22 22]
 [33 33 33]]
--------------------
[[ 1  1  1]
 [ 2  2  2]
 [ 3  3  3]
 [11 11 11]
 [22 22 22]
 [33 33 33]]
(6, 3) 2 vstack二维数组垂直组合，维度不变，列数不变，行数增加
[[ 1  1  1]
 [ 2  2  2]
 [ 3  3  3]
 [11 11 11]
 [22 22 22]
 [33 33 33]]
(6, 3) 2 concatenate与vstack二维数组垂直组合一样


深度组合：沿着纵轴方向组合

In [247]:
a1 = np.array([1,1,1])
b1 = np.array([2,2,2])

a2 = np.array([[1,1,1],
               [2,2,2],
               [3,3,3]])
b2 = np.array([[11,12,13],
               [21,22,23],
               [31,32,33]])

print(np.dstack((a1, b1)))
print("--------------------")
print(np.dstack((a2, b2)))

[[[1 2]
  [1 2]
  [1 2]]]
--------------------
[[[ 1 11]
  [ 1 12]
  [ 1 13]]

 [[ 2 21]
  [ 2 22]
  [ 2 23]]

 [[ 3 31]
  [ 3 32]
  [ 3 33]]]


## Numpy数组运算

https://zhuanlan.zhihu.com/p/53776362

In [272]:
a1 = np.array([1,1,1])
b1 = np.array([2,2,2])

a2 = np.array([[10,11,12],
               [20,21,22],
               [30,31,32]])
b2 = np.array([[10,11,12],
               [20,21,22],
               [30,31,32]])

In [297]:
print('a1+b1=\n',a1+b1)
print('a1*b1=\n',a1*b1)

print('a2+b2=\n',a2+b2)
print('a2*b2=\n',a2*b2)

a1+b1=
 [3 3 3]
a1*b1=
 [2 2 2]
a2+b2=
 [[12 12 12]
 [24 24 24]
 [36 36 36]]
a2*b2=
 [[11 11 11]
 [44 44 44]
 [99 99 99]]


从多元正态分布中抽取随机样本。
https://numpy.org/devdocs/reference/random/generated/numpy.random.multivariate_normal.html?highlight=numpy%20random%20multivariate_normal#numpy.random.multivariate_normal

参数
长度为 N 的 1-D array_like平均值
N 维分布的平均值。

cov2-D array_like，形状 （N， N）
分布的协方差矩阵。它必须是对称的和正半定的，才能进行适当的采样。

大小整数或整数元组，可选
例如，给定一个形状，生成样本，并以m-x-n-by-k排列方式打包。由于每个样本都是N维的，因此输出形状为 。如果未指定形状，则返回单个 （N-D） 样本。(m,n,k)m*n*k(m,n,k,N)

check_valid{ 'warn'， 'raise'， 'ignore' }， optional
协方差矩阵不是正半定时的行为。

托浮子，可选
检查协方差矩阵中的奇异值时的容差。在检查之前，cov被铸造成双倍。

返回
outndarray
绘制的样本，形状大小，如果提供的话。如果不是，则形状为 。(N,)

换句话说，每个条目都是从分布中得出的 N 维值。out[i,j,...,:]

In [8]:
mean = (1, 2)
cov = [[1, 0], [0, 1]]
x = np.random.multivariate_normal(mean, cov, (3, 3))
print(x)


[[[1.30430815 2.33173669]
  [2.4769841  3.34403045]
  [0.81296929 1.95826239]]

 [[0.67965149 0.19329475]
  [2.13564774 1.64814262]
  [1.5055785  1.78031201]]

 [[2.55227753 0.98660468]
  [1.49726159 1.52709532]
  [1.37450653 1.60078834]]]


In [25]:
import numpy as np
import random
print('生成随机数方法一: ', (random.choice([-1,1])))
print('运行时间:')
%timeit [random.choice([-1,1]) for i in range(1000)]
# 795 µs ± 15.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

生成随机数方法一:  -1
运行时间:
795 µs ± 15.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [26]:
print('生成随机数方法二: ', (1 if random.random() < 0.5 else -1))
print('运行时间:')
%timeit [1 if random.random() < 0.5 else -1 for i in range(1000)]
# 131 µs ± 9.71 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

生成随机数方法二:  -1
运行时间:
131 µs ± 9.71 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [27]:
print('生成随机数方法三:', (np.random.choice([-1,1],10)))
print('运行时间:')
%timeit np.random.choice([-1,1],size=1000)
#方法三最快
# 23.7 µs ± 906 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

生成随机数方法三: [ 1  1  1  1 -1  1  1 -1 -1 -1]
运行时间:
23.7 µs ± 906 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
